#!/usr/bin/env python3
"""Regression test: every user-facing page ships the canonical numeric layer.

Velora's global Latin-digit invariant is enforced at the DOM/Intl layer by
public/assets/velora-latin-digits.js (force -u-nu-latn on Intl.*, patched
toLocaleString*, MutationObserver over dynamic text) plus the canonical
localization loaders. If a new page is created without these includes, the
digit invariant silently regresses for that page. This test pins the include
set and load order (latin-digits must load before localization renders).

The page list is read from the git index (works in sparse checkouts and CI);
file content comes from the working tree when materialized, otherwise from
`git show HEAD:<path>` — so the whole repository is covered without checking
it out.
"""

import subprocess
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

# localized/**, en/**, fa/** are BUILD OUTPUTS (NP-5 — regenerated by
# tools/localization/build_localized_static.py from the source templates).
# They are covered by the deployed-page probe (check_key_references --page
# against the served catalog) plus the CSP manifest gate; hand-editing them is
# forbidden, so they are excluded from the source-side include contract.
EXCLUDED_DIRS = {"public", "api", "docs", "tools", "content", "_database",
                 "404", ".git", ".github", "node_modules",
                 "localized", "en", "fa"}
EXCLUDED_FILES = {"test-localization.html", "googleacbef8d6416f1474.html"}


def repo_pages(root: Path):
    listed = subprocess.run(
        ["git", "ls-files", "--cached"],
        cwd=str(root), capture_output=True, text=True, check=True,
    ).stdout.splitlines()
    pages = []
    for rel in listed:
        if rel.endswith("index.html") and "/" in rel:
            parts = Path(rel).parts
            if parts[0] in EXCLUDED_DIRS:
                continue
        elif rel.endswith(".html") and "/" in rel:
            continue
        elif rel.endswith(".html"):
            if Path(rel).name in EXCLUDED_FILES:
                continue
            pages.append(rel)
        else:
            continue
        if rel not in pages:
            pages.append(rel)
    return sorted(pages)


def read_page(root: Path, rel: str):
    p = root / rel
    if p.exists():  # materialized (incl. locally modified templates)
        return p.read_text(encoding="utf-8", errors="replace")
    return subprocess.run(
        ["git", "show", f"HEAD:{rel}"], cwd=str(root),
        capture_output=True, text=True, check=True,
    ).stdout


def check_page(html: str) -> list[str]:
    """Include contract per page category.

    - Every user-facing page must ship the canonical numeric layer
      (velora-latin-digits.js) — the global Latin-digit invariant.
    - Runtime-i18n pages (they include velora-localization.js) must also load
      velora-locale-registry.js and must load latin-digits BEFORE the
      localization loader (Intl patched before first render).
    - Static pages (privacy/terms/checkout) use build-time baking
      (data-i18n substituted by build_localized_static.py into localized/**)
      and therefore intentionally ship latin-digits without the runtime
      loader — that is the established architecture.
    """
    problems = []
    if "velora-latin-digits.js" not in html:
        problems.append("missing canonical numeric asset: velora-latin-digits.js")
    if "velora-localization.js" in html:
        if "velora-locale-registry.js" not in html:
            problems.append("runtime-i18n page missing velora-locale-registry.js")
        if html.index("velora-latin-digits.js") > html.index("velora-localization.js"):
            problems.append("velora-latin-digits.js must load BEFORE velora-localization.js")
    return problems


class LatinDigitCoverageTest(unittest.TestCase):
    def test_all_pages_include_canonical_numeric_layer(self):
        pages = repo_pages(ROOT)
        self.assertGreater(len(pages), 20, "page discovery broken?")
        bad = {}
        for rel in pages:
            problems = check_page(read_page(ROOT, rel))
            if problems:
                bad[rel] = problems
        self.assertEqual(
            bad, {},
            f"{len(bad)} pages missing the canonical numeric/locale layer: {bad}")

    def test_negative_fixture_caught(self):
        with tempfile.TemporaryDirectory() as td:
            p = Path(td) / "index.html"
            p.write_text("<html><body>hi</body></html>", encoding="utf-8")
            problems = check_page(p.read_text(encoding="utf-8"))
            self.assertTrue(any("velora-latin-digits.js" in x for x in problems))


if __name__ == "__main__":
    unittest.main(verbosity=2)
