#!/usr/bin/env python3
"""
VELORA Environment Management System — reusable, environment-aware, approval-gated
deployment & database-management engine.

Targets:   staging | production   (ALWAYS explicit; never inferred, never fall back)
Modes:     inspect | plan | backup | migrate | deploy | verify   (default = inspect/plan = READ-ONLY)

This module is PURE LOGIC. It performs NO network I/O, NO SQL execution, NO file
mutation outside the audit artifacts it is told to write. The actual DB transport is
the proven GitHub Actions -> FTP -> one-use PHP probe -> Database::connection() path
(see ops/velora-mgmt/probe/*.php and .github/workflows/velora-mgmt.yml); this engine
consumes the probe's read-only metadata JSON and produces deterministic plans/hashes
and approval decisions.

Hard rules enforced here:
  * target environment must be explicit and is validated against an allow-list.
  * no credential mixing / no cross-environment fallback.
  * an approval is bound to (environment, operation, commit_sha, migration_versions,
    plan_hash) and is invalid if ANY of those change.
  * production mutating operations require a verified backup in addition to approval.
  * no destructive SQL (DROP DATABASE/TABLE, TRUNCATE, DELETE) is ever generated by the
    migration planner; rollback is a separate, explicitly-approved mechanism.

The engine never prints secret values.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from dataclasses import dataclass, field, asdict

try:
    import backup as bk  # sibling module in ops/velora-mgmt
except ImportError:  # when imported as package / different cwd
    import os as _os, sys as _sys
    _sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__)))
    import backup as bk
from typing import Any

# --------------------------------------------------------------------------- #
# Environment model
# --------------------------------------------------------------------------- #

ENVIRONMENTS = ("staging", "production")
OPERATIONS = ("inspect", "plan", "backup", "migrate", "deploy", "verify")
READ_ONLY_OPERATIONS = ("inspect", "plan", "verify")

# Credential / transport mapping. Values are SECRET *names* only (never values).
# Staging and production use strictly separate credentials; the selector refuses to
# mix them and never falls back.
ENV_CONFIG = {
    "staging": {
        "ftp_secrets": ("STAGING_FTP_SERVER", "STAGING_FTP_USERNAME", "STAGING_FTP_PASSWORD"),
        "env_secret": "STAGING_VELORA_ENV",
        "ftp_docroot": "public_html/staging.veloratrade.ir/",
        "private_root": "velora_private_staging",
        "base_url": "https://staging.veloratrade.ir",
        "github_environment": None,  # staging uses repo-level secrets; no protected env
        "backup_required_before_change": False,  # lighter policy, BUT migrate still gated (see PLAN)
    },
    "production": {
        "ftp_secrets": ("FTP_SERVER", "FTP_USERNAME", "FTP_PASSWORD"),
        "env_secret": None,  # production env config lives in the production private root
        "ftp_docroot": "public_html/",
        "private_root": "velora_private",
        "base_url": "https://veloratrade.ir",
        "github_environment": "production",  # protected GitHub environment (required reviewers)
        "backup_required_before_change": True,  # MANDATORY verified backup before any change
    },
}

# Repository-defined migration order (oldest -> newest). v1.0 MUST precede v1.1.
MIGRATION_ORDER = ["v1.0", "v1.1"]
MIGRATION_FILES = {
    "v1.0": "api/database/migrations/v1.0_trade_time_canonical.sql",
    "v1.1": "api/database/migrations/v1.1_metaapi_fill_ledger.sql",
}

# SQL that the migration system is never allowed to emit as part of a normal operation.
FORBIDDEN_SQL_PATTERNS = [
    r"\bDROP\s+DATABASE\b",
    r"\bDROP\s+TABLE\b",
    r"\bTRUNCATE\b",
    r"\bDELETE\s+FROM\b",
    r"\bGRANT\b",
    r"\bREVOKE\b",
]


class VeloraMgmtError(Exception):
    pass


# --------------------------------------------------------------------------- #
# Validation helpers
# --------------------------------------------------------------------------- #

def require_environment(env: str) -> dict:
    if env not in ENVIRONMENTS:
        raise VeloraMgmtError(
            f"target environment must be explicit and one of {ENVIRONMENTS}; got {env!r}"
        )
    return ENV_CONFIG[env]


def require_operation(op: str) -> None:
    if op not in OPERATIONS:
        raise VeloraMgmtError(f"operation must be one of {OPERATIONS}; got {op!r}")


def is_read_only(op: str) -> bool:
    return op in READ_ONLY_OPERATIONS


def redact_db_name(name: str | None) -> str:
    """Database names may encode the account; mask the account-prefix but keep the
    environment suffix so audit output is useful without leaking the account id."""
    if not name:
        return "<unknown>"
    if "_" in name:
        head, _, tail = name.rpartition("_")
        return f"***_{tail}"
    return "***"


# --------------------------------------------------------------------------- #
# Normalized schema model
# --------------------------------------------------------------------------- #

@dataclass
class Column:
    name: str
    column_type: str          # e.g. varchar(64), bigint unsigned, datetime
    data_type: str            # e.g. varchar, bigint, datetime
    is_nullable: bool
    column_default: str | None
    ordinal_position: int

    def signature(self) -> str:
        d = "NULL" if self.is_nullable else "NOT NULL"
        default = "" if self.column_default is None else f" DEFAULT {self.column_default}"
        return f"{self.name} {self.column_type} {d}{default}"


@dataclass
class Index:
    name: str
    columns: list[str]
    unique: bool


@dataclass
class ForeignKey:
    name: str
    column: str
    ref_table: str
    ref_column: str


@dataclass
class Table:
    name: str
    engine: str | None = None
    table_type: str | None = None
    collation: str | None = None
    table_rows: int | None = None
    exists: bool = True
    columns: list[Column] = field(default_factory=list)
    indexes: list[Index] = field(default_factory=list)
    foreign_keys: list[ForeignKey] = field(default_factory=list)


@dataclass
class Schema:
    database: str | None = None
    engine_version: str | None = None
    charset_server: str | None = None
    collation_server: str | None = None
    charset_database: str | None = None
    collation_database: str | None = None
    sql_mode: str | None = None
    transaction_isolation: str | None = None
    tables: dict[str, Table] = field(default_factory=dict)

    def table_names(self) -> list[str]:
        return sorted(self.tables)


# --------------------------------------------------------------------------- #
# Probe metadata (ACTUAL state) -> normalized Schema
# --------------------------------------------------------------------------- #

def _tf(v: Any) -> bool:
    return str(v).upper() == "YES"


def schema_from_probe(meta: dict) -> Schema:
    """Normalize the read-only probe JSON (produced by the PHP probe) into a Schema.

    Expected probe shape (see ops/velora-mgmt/probe/inspect.php):
      scalars: {VERSION:{rows:[{v:..}]}, sql_mode:{rows:[{v:..}]}, ...}
      tables:  {rows:[{TABLE_NAME,ENGINE,TABLE_TYPE,TABLE_COLLATION,TABLE_ROWS}, ...]}
      focus:   {<table>: {exists:bool, columns:{rows:[...]}, statistics:{rows:[...]},
                          key_usage:{rows:[...]}}}
    Only information_schema / @@ metadata is consumed; no row data.
    """
    sc = meta.get("scalars", {})

    def scalar(key: str) -> str | None:
        node = sc.get(key) or {}
        if not node.get("ok"):
            return None
        rows = node.get("rows") or []
        if not rows:
            return None
        row = rows[0]
        if "v" in row:
            return row["v"]
        # SHOW VARIABLES style: {Variable_name, Value}
        return row.get("Value")

    s = Schema(
        database=scalar("current_database"),
        engine_version=scalar("VERSION"),
        charset_server=scalar("character_set_server"),
        collation_server=scalar("collation_server"),
        charset_database=scalar("character_set_database"),
        collation_database=scalar("collation_database"),
        sql_mode=scalar("sql_mode") or "",
        transaction_isolation=scalar("transaction_isolation"),
    )

    for row in (meta.get("tables", {}).get("rows") or []):
        tname = row["TABLE_NAME"]
        s.tables[tname] = Table(
            name=tname,
            engine=row.get("ENGINE"),
            table_type=row.get("TABLE_TYPE"),
            collation=row.get("TABLE_COLLATION"),
            table_rows=row.get("TABLE_ROWS"),
            exists=True,
        )

    for tname, entry in (meta.get("focus") or {}).items():
        if not entry.get("exists"):
            # table explicitly reported missing
            s.tables.setdefault(tname, Table(name=tname, exists=False))
            s.tables[tname].exists = False
            continue
        t = s.tables.setdefault(tname, Table(name=tname, exists=True))
        t.exists = True
        for c in (entry.get("columns", {}).get("rows") or []):
            t.columns.append(Column(
                name=c["COLUMN_NAME"],
                column_type=c["COLUMN_TYPE"],
                data_type=c.get("DATA_TYPE", ""),
                is_nullable=_tf(c.get("IS_NULLABLE")),
                column_default=c.get("COLUMN_DEFAULT"),
                ordinal_position=int(c.get("ORDINAL_POSITION", 0)),
            ))
        # group statistics by index
        idx: dict[str, dict] = {}
        for st in (entry.get("statistics", {}).get("rows") or []):
            name = st["INDEX_NAME"]
            g = idx.setdefault(name, {"cols": {}, "non_unique": int(st.get("NON_UNIQUE", 1))})
            g["cols"][int(st["SEQ_IN_INDEX"])] = st["COLUMN_NAME"]
        for name, g in idx.items():
            cols = [g["cols"][k] for k in sorted(g["cols"])]
            t.indexes.append(Index(name=name, columns=cols, unique=(g["non_unique"] == 0)))
        seen_fk: dict[str, ForeignKey] = {}
        for ku in (entry.get("key_usage", {}).get("rows") or []):
            cname = ku["CONSTRAINT_NAME"]
            ref_t = ku.get("REFERENCED_TABLE_NAME")
            fk = seen_fk.get(cname) or ForeignKey(
                name=cname, column=ku["COLUMN_NAME"],
                ref_table=ref_t or "", ref_column=ku.get("REFERENCED_COLUMN_NAME") or "")
            seen_fk[cname] = fk
        t.foreign_keys = list(seen_fk.values())
    return s


# --------------------------------------------------------------------------- #
# EXPECTED schema — derived from repository baseline schema.sql + migrations
# --------------------------------------------------------------------------- #

def _read(path: str) -> str:
    with open(path, "r", encoding="utf-8") as fh:
        return fh.read()


def _strip_sql_comments(sql: str) -> str:
    sql = re.sub(r"--[^\n]*", "", sql)
    sql = re.sub(r"/\*.*?\*/", "", sql, flags=re.S)
    return sql


def _split_top_level(body: str) -> list[str]:
    """Split a CREATE TABLE body on commas at parenthesis depth 0."""
    parts: list[str] = []
    depth = 0
    buf = ""
    for ch in body:
        if ch == "(":
            depth += 1; buf += ch
        elif ch == ")":
            depth -= 1; buf += ch
        elif ch == "," and depth == 0:
            parts.append(buf); buf = ""
        else:
            buf += ch
    if buf.strip():
        parts.append(buf)
    return parts


def _extract_create_block(sql: str, start: int) -> tuple[str, str, int]:
    """Given index of the '(' opening a CREATE TABLE body, return (body, tail, end_index)
    by balancing parentheses. tail = text after the matching ')' up to the statement ';'."""
    assert sql[start] == "("
    depth = 0
    i = start
    while i < len(sql):
        if sql[i] == "(":
            depth += 1
        elif sql[i] == ")":
            depth -= 1
            if depth == 0:
                body = sql[start + 1:i]
                semi = sql.find(";", i)
                tail = sql[i + 1:semi if semi != -1 else len(sql)]
                return body, tail, (semi if semi != -1 else len(sql))
        i += 1
    return sql[start + 1:], "", len(sql)


def _parse_coldef(p: str, pos: int) -> Column | None:
    cm = re.match(r"`?(\w+)`?\s+(.*)$", p, re.S)
    if not cm:
        return None
    cname = cm.group(1)
    rest = re.sub(r"\s+", " ", cm.group(2).strip())
    tm = re.match(r"([a-zA-Z]+(?:\s*\([^)]*\))?(?:\s+(?:unsigned|zerofill))*)", rest, re.I)
    full_type = tm.group(1).strip() if tm else rest.split()[0]
    nullable = "NOT NULL" not in rest.upper()
    dm = re.search(r"DEFAULT\s+('(?:[^']*)'|[A-Za-z0-9_.()]+)", rest, re.I)
    default = dm.group(1) if dm else None
    return Column(name=cname, column_type=_norm_type(full_type),
                  data_type=re.split(r"[ (]", full_type)[0].lower(),
                  is_nullable=nullable, column_default=default, ordinal_position=pos)


def _parse_create_tables(sql: str) -> dict[str, dict]:
    """Purpose-specific parser for the project's CREATE TABLE blocks (proper paren
    balancing). Returns {table: {columns, indexes, fks, engine, charset, collation}}."""
    out: dict[str, dict] = {}
    for m in re.finditer(r"CREATE\s+TABLE(?:\s+IF\s+NOT\s+EXISTS)?\s+`?(\w+)`?\s*\(",
                         sql, flags=re.S | re.IGNORECASE):
        tname = m.group(1)
        open_paren = sql.find("(", m.start())
        body, tail, _ = _extract_create_block(sql, open_paren)
        cols: list[Column] = []
        indexes: list[Index] = []
        fks: list[ForeignKey] = []
        pos = 0
        for part in _split_top_level(body):
            p = re.sub(r"\s+", " ", part.strip())
            up = p.upper()
            if up.startswith("PRIMARY KEY"):
                inner = p[p.find("(") + 1:p.rfind(")")]
                keycols = [x.strip("` ") for x in inner.split(",")]
                indexes.append(Index(name="PRIMARY", columns=keycols, unique=True))
            elif up.startswith("UNIQUE KEY") or up.startswith("UNIQUE INDEX"):
                mm = re.match(r"UNIQUE\s+(?:KEY|INDEX)\s+`?(\w+)`?\s*\((.*)\)\s*$", p, re.I | re.S)
                if mm:
                    cc = [x.strip("` ") for x in mm.group(2).split(",")]
                    indexes.append(Index(name=mm.group(1), columns=cc, unique=True))
            elif up.startswith("KEY ") or up.startswith("INDEX "):
                mm = re.match(r"(?:KEY|INDEX)\s+`?(\w+)`?\s*\((.*)\)\s*$", p, re.I | re.S)
                if mm:
                    cc = [x.strip("` ") for x in mm.group(2).split(",")]
                    indexes.append(Index(name=mm.group(1), columns=cc, unique=False))
            elif up.startswith("CONSTRAINT") and "FOREIGN KEY" in up:
                mm = re.match(r"CONSTRAINT\s+`?(\w+)`?\s+FOREIGN\s+KEY\s*\(`?(\w+)`?\)\s*"
                              r"REFERENCES\s+`?(\w+)`?\s*\(`?(\w+)`?\)", p, re.I | re.S)
                if mm:
                    fks.append(ForeignKey(name=mm.group(1), column=mm.group(2),
                                          ref_table=mm.group(3), ref_column=mm.group(4)))
            elif re.match(r"^`?\w+`?\s+", p):
                pos += 1
                c = _parse_coldef(p, pos)
                if c:
                    cols.append(c)
        eng = charset = coll = None
        em = re.search(r"ENGINE\s*=\s*(\w+)", tail, re.I)
        if em: eng = em.group(1)
        cm2 = re.search(r"DEFAULT\s+CHARSET\s*=\s*(\w+)", tail, re.I)
        if cm2: charset = cm2.group(1)
        clm = re.search(r"COLLATE\s*=?\s*(\w+)", tail, re.I)
        if clm: coll = clm.group(1)
        out[tname] = {"columns": cols, "indexes": indexes, "fks": fks,
                      "engine": eng, "charset": charset, "collation": coll}
    return out


def _norm_type(t: str) -> str:
    t = re.sub(r"\s+", " ", t.strip())
    # lowercase the type keyword but preserve enum/set value case for comparison
    m = re.match(r"^([a-z]+)(.*)$", t, re.I)
    if m and m.group(1).lower() in ("enum", "set"):
        return m.group(1).lower() + re.sub(r"\s+", "", m.group(2))
    return re.sub(r"\s+", " ", t.lower())


def _norm_default(d: str | None) -> str | None:
    if d is None:
        return None
    d = d.strip()
    if len(d) >= 2 and d[0] == "'" and d[-1] == "'":
        d = d[1:-1]  # string default: compare unquoted value
    return d


def expected_schema(repo_root: str) -> Schema:
    """Build EXPECTED state at HEAD: baseline schema.sql plus additive migrations
    v1.0 and v1.1 (both ship in the repo and define the target schema)."""
    schema_sql = _read(os.path.join(repo_root, "api/database/schema.sql"))
    tables = _parse_create_tables(_strip_sql_comments(schema_sql))

    # --- v1.0: additive ALTERs (apply to expected baseline). The migration wraps
    # each statement in a SET @sql = IF(..., 'ALTER TABLE ... ADD COLUMN ...', 'SELECT 1');
    # so parse the ALTER text inside those string literals. ---
    v10 = _strip_sql_comments(_read(os.path.join(repo_root, MIGRATION_FILES["v1.0"])))
    for am in re.finditer(r"ALTER TABLE (\w+) ADD COLUMN (\w+) (.+?)(?: AFTER \w+)?',", v10, re.I):
        tname, cname, spec = am.group(1), am.group(2), am.group(3).strip()
        spec = spec.rstrip("'")
        ent = tables.setdefault(tname, {"columns": [], "indexes": [], "fks": [],
                                        "engine": "InnoDB", "charset": "utf8mb4",
                                        "collation": "utf8mb4_unicode_ci"})
        tm = re.match(r"([a-zA-Z]+(?:\s+unsigned)?(?:\s*\([^)]*\))?)", spec)
        full_type = tm.group(1).strip() if tm else spec.split()[0]
        nullable = "NOT NULL" not in spec.upper()
        dm = re.search(r"DEFAULT\s+('(?:[^']*)'|[A-Za-z0-9_.]+)", spec, re.I)
        default = dm.group(1) if dm else None
        ent["columns"].append(Column(
            name=cname, column_type=_norm_type(full_type),
            data_type=full_type.split("(")[0].split()[0],
            is_nullable=nullable, column_default=default,
            ordinal_position=len(ent["columns"]) + 1))
    # ADD KEY / ADD UNIQUE KEY
    for im in re.finditer(r"ALTER TABLE (\w+) ADD (?:UNIQUE )?KEY (\w+) \(([^)]*)\)',", v10, re.I):
        tname, iname, cols = im.group(1), im.group(2), im.group(3)
        unique = "UNIQUE" in im.group(0).upper().split("KEY")[0]
        cc = [x.strip("` ") for x in cols.split(",")]
        tables[tname]["indexes"].append(Index(name=iname, columns=cc, unique=unique))

    # --- v1.1: CREATE TABLE metaapi_fills ---
    v11 = _strip_sql_comments(_read(os.path.join(repo_root, MIGRATION_FILES["v1.1"])))
    for tname, ent in _parse_create_tables(v11).items():
        tables[tname] = ent

    s = Schema(database="<expected>", engine_version="MySQL 8.0 / MariaDB 11 (target)")
    for tname, ent in tables.items():
        s.tables[tname] = Table(
            name=tname, engine=ent.get("engine"), table_type="BASE TABLE",
            collation=ent.get("collation"), columns=ent["columns"],
            indexes=ent["indexes"], foreign_keys=ent["fks"], exists=True)
    return s


# --------------------------------------------------------------------------- #
# Schema comparison (ACTUAL vs EXPECTED)
# --------------------------------------------------------------------------- #

def _colmap(t: Table) -> dict[str, Column]:
    return {c.name: c for c in t.columns}


def compare(actual: Schema, expected: Schema) -> dict:
    """Deterministic structural diff. Read-only; never mutates. Unexpected tables/
    columns are REPORTED, never auto-fixed."""
    diff: dict[str, Any] = {
        "missing_tables": [],
        "unexpected_tables": [],
        "tables": {},
        "engine_notes": [],
    }
    exp_names = set(expected.tables)
    act_names = {n for n, t in actual.tables.items() if t.exists}

    for t in sorted(exp_names - act_names):
        diff["missing_tables"].append(t)
    # tables present in actual but not expected (report for review; never auto-fix)
    for t in sorted(act_names - exp_names):
        diff["unexpected_tables"].append(t)

    for tname in sorted(exp_names):
        et = expected.tables[tname]
        at = actual.tables.get(tname)
        td: dict[str, Any] = {"exists": bool(at and at.exists), "missing_columns": [],
                              "type_mismatches": [], "nullability_mismatches": [],
                              "default_mismatches": [], "missing_indexes": [],
                              "missing_foreign_keys": [], "engine_mismatch": None,
                              "collation_mismatch": None, "column_detail_captured": False}
        # Missing entirely from actual, or explicitly reported exists=False.
        if at is None or not at.exists:
            if tname not in [t for t in diff["missing_tables"]]:
                pass
            diff["tables"][tname] = td
            if at is None:
                # not already listed via exp-act name sets only when exists=True
                if tname not in diff["missing_tables"]:
                    diff["missing_tables"].append(tname)
            continue
        # Exists but column-level metadata was not captured (probe only details focus
        # tables): report existence/engine, do NOT fabricate missing columns.
        if not at.columns and et.columns:
            td["column_detail_captured"] = False
            if et.engine and at.engine and at.engine.lower() != et.engine.lower():
                td["engine_mismatch"] = {"actual": at.engine, "expected": et.engine}
            diff["tables"][tname] = td
            continue
        td["column_detail_captured"] = True
        ac, ec = _colmap(at), _colmap(et)
        for cname in ec:
            if cname not in ac:
                td["missing_columns"].append(cname); continue
            a, e = ac[cname], ec[cname]
            if _norm_type(a.column_type) != _norm_type(e.column_type):
                td["type_mismatches"].append({"column": cname,
                    "actual": a.column_type, "expected": e.column_type})
            if a.is_nullable != e.is_nullable:
                td["nullability_mismatches"].append({"column": cname,
                    "actual": a.is_nullable, "expected": e.is_nullable})
            if (a.column_default or None) != (e.column_default or None):
                td["default_mismatches"].append({"column": cname,
                    "actual": a.column_default, "expected": e.column_default})
        aidx = {i.name: i for i in at.indexes}
        for i in et.indexes:
            if i.name not in aidx:
                td["missing_indexes"].append({"name": i.name, "columns": i.columns,
                                              "unique": i.unique})
        afk = {f.name: f for f in at.foreign_keys}
        for f in et.foreign_keys:
            if f.name not in afk:
                td["missing_foreign_keys"].append({"name": f.name, "column": f.column,
                                                   "ref": f"{f.ref_table}.{f.ref_column}"})
        if et.engine and at.engine and at.engine.lower() != et.engine.lower():
            td["engine_mismatch"] = {"actual": at.engine, "expected": et.engine}
        if et.collation and at.collation and at.collation.lower() != et.collation.lower():
            td["collation_mismatch"] = {"actual": at.collation, "expected": et.collation}
        diff["tables"][tname] = td
    return diff


# --------------------------------------------------------------------------- #
# Migration planning
# --------------------------------------------------------------------------- #

def _migration_provides(version: str) -> dict:
    """Which expected objects each migration introduces (used to attribute diffs)."""
    provides = {
        "v1.0": {"tables": [], "columns": {
            "trades": ["occurred_open_at_utc", "occurred_close_at_utc", "time_status",
                       "source_timezone", "source_timezone_source", "source_calendar",
                       "raw_open_text", "raw_close_text"],
            "trading_accounts": ["timezone", "timezone_source"]},
            "indexes": {"trades": ["idx_trades_occurred_open", "idx_trades_time_status"]}},
        "v1.1": {"tables": ["metaapi_fills"], "columns": {}, "indexes": {}},
    }
    return provides[version]


def pending_migrations(actual: Schema, expected: Schema) -> list[str]:
    """Deterministically decide which repo migrations are NOT yet applied, using
    structural signatures (not a migration table). v1.0 applied iff all its columns
    and indexes exist; v1.1 applied iff metaapi_fills exists."""
    pending = []
    prov = _migration_provides("v1.0")
    t = actual.tables.get("trades")
    ta = actual.tables.get("trading_accounts")
    tcols = {c.name for c in t.columns} if t and t.exists else set()
    ta_cols = {c.name for c in ta.columns} if ta and ta.exists else set()
    tidx = {i.name for i in t.indexes} if t and t.exists else set()
    v10_present = (
        all(c in tcols for c in prov["columns"]["trades"]) and
        all(c in ta_cols for c in prov["columns"]["trading_accounts"]) and
        all(i in tidx for i in prov["indexes"]["trades"])
    )
    if not v10_present:
        pending.append("v1.0")
    mf = actual.tables.get("metaapi_fills")
    if not (mf and mf.exists):
        pending.append("v1.1")
    # enforce order
    return [v for v in MIGRATION_ORDER if v in pending]


def plan_hash(plan: dict) -> str:
    """Stable hash over the migration-relevant content of a plan."""
    canonical = json.dumps({
        "environment": plan["environment"],
        "operation": plan["operation"],
        "commit_sha": plan["commit_sha"],
        "migrations": plan["migrations"],
        "expected_ops": plan["expected_operations"],
    }, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode()).hexdigest()


def build_plan(environment: str, actual: Schema, commit_sha: str,
               repo_root: str | None = None) -> dict:
    require_environment(environment)
    expected = expected_schema(repo_root or os.getcwd())
    diff = compare(actual, expected)
    pending = pending_migrations(actual, expected)

    expected_ops: list[dict] = []
    for v in pending:
        if v == "v1.0":
            expected_ops.append({
                "migration": "v1.0", "file": MIGRATION_FILES["v1.0"],
                "kind": "additive ALTER (idempotent, information_schema-guarded)",
                "objects": "trades +8 columns/+2 indexes; trading_accounts +2 columns",
                "destructive": False})
        elif v == "v1.1":
            expected_ops.append({
                "migration": "v1.1", "file": MIGRATION_FILES["v1.1"],
                "kind": "CREATE TABLE IF NOT EXISTS metaapi_fills (InnoDB/utf8mb4)",
                "objects": "metaapi_fills + unique(account_id,external_deal_id) + indexes",
                "destructive": False})

    # safety: scan migration files for forbidden destructive SQL (defense in depth)
    forbidden_hits = []
    for v in pending:
        sql = _read(os.path.join(repo_root or os.getcwd(), MIGRATION_FILES[v])).upper()
        for pat in FORBIDDEN_SQL_PATTERNS:
            if re.search(pat, sql):
                forbidden_hits.append({"migration": v, "pattern": pat})

    cfg = ENV_CONFIG[environment]
    plan = {
        "plan_version": 1,
        "environment": environment,
        "operation": "migrate",
        "commit_sha": commit_sha,
        "current_database": {
            "engine_version": actual.engine_version,
            "database": redact_db_name(actual.database),
            "charset": actual.charset_database,
            "collation": actual.collation_database,
            "sql_mode": actual.sql_mode,
            "transaction_isolation": actual.transaction_isolation,
            "table_count": len([t for t in actual.tables.values() if t.exists]),
        },
        "detected_differences": diff,
        "migrations": pending,
        "expected_operations": expected_ops,
        "forbidden_sql_hits": forbidden_hits,
        "risk": ("LOW — additive, nullable, idempotent, no backfill, no destructive SQL"
                 if pending and not forbidden_hits else
                 ("NONE — no pending migrations" if not pending else "REVIEW — forbidden SQL detected")),
        "backup_requirement": {
            "required": cfg["backup_required_before_change"],
            "state": "UNVERIFIED",  # never assumed; must be proven before migrate
            "note": ("Production: verified pre-change backup is MANDATORY."
                     " Staging: migrate stays BLOCKED until a verified backup/rollback is evidenced.")
        },
        "approval": {"state": "WAITING_FOR_EXPLICIT_APPROVAL"},
        "execution": "BLOCKED",
    }
    plan["plan_hash"] = plan_hash(plan)
    return plan


# --------------------------------------------------------------------------- #
# Approval binding
# --------------------------------------------------------------------------- #

@dataclass
class Approval:
    environment: str
    operation: str
    commit_sha: str
    migrations: list[str]
    plan_hash: str
    state: str = "APPROVED"

    @staticmethod
    def from_token(token: dict) -> "Approval":
        return Approval(
            environment=token["environment"], operation=token["operation"],
            commit_sha=token["commit_sha"], migrations=sorted(token.get("migrations", [])),
            plan_hash=token["plan_hash"], state=token.get("state", "APPROVED"))


def validate_approval(plan: dict, approval: Approval | None,
                      backup_verified: bool, target_environment: str) -> dict:
    """Return a decision. Production mutating ops additionally require a verified
    backup; approval is environment-scoped and bound to exact commit/migrations/hash."""
    reasons: list[str] = []
    env = plan["environment"]
    if target_environment != env:
        reasons.append(f"target mismatch: requested {target_environment} but plan is for {env}")
    if approval is None:
        reasons.append("no approval supplied")
    else:
        if approval.environment != env:
            reasons.append(f"approval is for {approval.environment}, cannot authorize {env}")
        if approval.operation != plan["operation"]:
            reasons.append("approval operation mismatch")
        if approval.commit_sha != plan["commit_sha"]:
            reasons.append("approval commit_sha mismatch")
        if sorted(approval.migrations) != sorted(plan["migrations"]):
            reasons.append("approval migration set mismatch")
        if approval.plan_hash != plan["plan_hash"]:
            reasons.append("approval plan_hash mismatch (plan changed; re-approval required)")
    cfg = ENV_CONFIG[env]
    if cfg["backup_required_before_change"] and not backup_verified:
        reasons.append("production change requires a VERIFIED pre-change backup (none verified)")
    if plan["forbidden_sql_hits"]:
        reasons.append("plan contains forbidden/destructive SQL")
    allowed = not reasons
    return {"allowed": allowed, "decision": "EXECUTE" if allowed else "STOP", "reasons": reasons}


# --------------------------------------------------------------------------- #
# Audit artifact
# --------------------------------------------------------------------------- #

def audit_record(environment: str, operation: str, commit_sha: str, run_id: str,
                 plan_hash: str | None, approval_state: str, backup_state: str,
                 result: str, verification: str | None = None) -> dict:
    require_environment(environment)
    return {
        "timestamp_utc": os.environ.get("VELORA_AUDIT_TIME"),  # set by CI; else omitted
        "environment": environment,
        "repository": "veloratrade/veloratrade",
        "commit_sha": commit_sha,
        "workflow_run_id": run_id,
        "operation": operation,
        "plan_hash": plan_hash,
        "approval_state": approval_state,
        "backup_state": backup_state,
        "result": result,
        "verification_result": verification,
    }


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #

def _cmd_inspect(args) -> int:
    meta = json.load(open(args.metadata, encoding="utf-8"))
    s = schema_from_probe(meta)
    out = {
        "environment": args.environment,
        "database": redact_db_name(s.database),
        "engine_version": s.engine_version,
        "charset_server": s.charset_server,
        "collation_server": s.collation_server,
        "charset_database": s.charset_database,
        "collation_database": s.collation_database,
        "sql_mode": s.sql_mode,
        "transaction_isolation": s.transaction_isolation,
        "tables": [
            {"name": t.name, "exists": t.exists, "engine": t.engine, "type": t.table_type,
             "collation": t.collation, "rows_estimate": t.table_rows,
             "columns": len(t.columns), "indexes": len(t.indexes),
             "foreign_keys": len(t.foreign_keys)}
            for t in (s.tables[n] for n in s.table_names())
        ],
    }
    print(json.dumps(out, indent=2, ensure_ascii=False))
    return 0


def _cmd_plan(args) -> int:
    meta = json.load(open(args.metadata, encoding="utf-8"))
    s = schema_from_probe(meta)
    plan = build_plan(args.environment, s, args.commit_sha, repo_root=args.repo_root)
    print(json.dumps(plan, indent=2, ensure_ascii=False))
    return 0


def _cmd_verify(args) -> int:
    meta = json.load(open(args.metadata, encoding="utf-8"))
    s = schema_from_probe(meta)
    expected = expected_schema(args.repo_root)
    diff = compare(s, expected)
    pending = pending_migrations(s, expected)
    # verification for a migrate op: the planned migrations must now be applied
    ok = not pending
    print(json.dumps({"verification": "PASS" if ok else "FAIL",
                      "pending_migrations": pending,
                      "diff_summary": {
                          "missing_tables": diff["missing_tables"],
                          "unexpected_tables": diff["unexpected_tables"],
                          "tables_with_missing_columns": {
                              k: v["missing_columns"] for k, v in diff["tables"].items()
                              if v.get("missing_columns")},
                      }}, indent=2, ensure_ascii=False))
    return 0 if ok else 1



def _cmd_backup_discover(args) -> int:
    """Read-only backup discovery from a GitHub Actions artifact listing JSON.
    Reports file + database backup manifests and the mutation gate decision, and
    explicitly reports when no database backup mechanism exists (never fabricates)."""
    artifacts = []
    if args.artifacts:
        data = json.load(open(args.artifacts, encoding="utf-8"))
        artifacts = data.get("artifacts", data if isinstance(data, list) else [])
    out = {"environment": args.environment, "file_backups": [], "database_backups": []}
    # FILE backups (real mechanism = production deploy artifact)
    fman = bk.manifest_from_github_artifacts(args.environment, artifacts)
    fgate = bk.mutation_backup_gate(fman, args.environment, "file")
    out["file_backups"] = {
        "count": len(fman.records),
        "gate": fgate.__dict__,
        "records": [r.to_dict() for r in fman.sorted_newest_first()],
        "mechanism": ("IMPLEMENTED (deploy.yml pre-deploy docroot tar -> GitHub "
                      "artifact, retention 14d)") if args.environment == "production"
                     else "NOT IMPLEMENTED (deploy-staging.yml has no backup step)",
    }
    # DATABASE backups (no implemented dump mechanism -> empty manifest => BLOCKED)
    dman = bk.database_backup_manifest(args.environment)
    dgate = bk.mutation_backup_gate(dman, args.environment, "database")
    out["database_backups"] = {
        "count": 0,
        "gate": dgate.__dict__,
        "mechanism": ("NO VERIFIED DATABASE BACKUP MECHANISM FOUND (no mysqldump/"
                      "snapshot workflow; preflight_v0_2 only verifies an operator-"
                      "supplied dump and is not wired to CI)"),
    }
    print(json.dumps(out, indent=2, ensure_ascii=False))
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="velora-mgmt")
    sub = ap.add_subparsers(dest="cmd", required=True)

    def common(p, ro=True):
        p.add_argument("--environment", required=True, choices=ENVIRONMENTS)
        p.add_argument("--metadata", required=True, help="probe read-only metadata JSON")
        p.add_argument("--repo-root", default=os.getcwd())

    pi = sub.add_parser("inspect"); common(pi); pi.set_defaults(fn=_cmd_inspect)
    pp = sub.add_parser("plan"); common(pp)
    pp.add_argument("--commit-sha", required=True); pp.set_defaults(fn=_cmd_plan)
    pv = sub.add_parser("verify"); common(pv); pv.set_defaults(fn=_cmd_verify)
    pb = sub.add_parser("backup-discover")
    pb.add_argument("--environment", required=True, choices=ENVIRONMENTS)
    pb.add_argument("--artifacts", help="read-only GitHub Actions artifact listing JSON")
    pb.set_defaults(fn=_cmd_backup_discover)

    args = ap.parse_args(argv)
    require_environment(args.environment)
    return args.fn(args)


if __name__ == "__main__":
    sys.exit(main())
