#!/usr/bin/env python3
"""Compile the tiny first-paint locale registry from the central manifest.

Catalog messages are intentionally excluded. Initial HTML is localized at build time and
runtime messages are loaded from feature chunks for the active locale only.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "public/locales/manifest.json"
TARGET = ROOT / "public/assets/velora-locale-registry.js"


def main() -> None:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    required = (
        "version", "defaultLocale", "fallbackLocale", "storageKey",
        "cookieKey", "featureCatalogBase", "locales",
    )
    missing = [key for key in required if key not in manifest]
    if missing:
        raise SystemExit("Manifest is missing: " + ", ".join(missing))
    entries = manifest["locales"]
    if not isinstance(entries, dict):
        raise SystemExit("manifest.locales must be an object keyed by locale code")
    enabled = {code: metadata for code, metadata in entries.items() if metadata.get("enabled", True)}
    for special in (manifest["defaultLocale"], manifest["fallbackLocale"]):
        if special not in enabled:
            raise SystemExit(f"Required locale is not enabled: {special}")
    for code in enabled:
        catalog = ROOT / f"public/locales/{code}.json"
        if not catalog.is_file():
            raise SystemExit(f"Enabled locale has no catalog: {code}")

    browser_registry = {key: manifest[key] for key in required}
    payload = json.dumps(browser_registry, ensure_ascii=False, separators=(",", ":"))
    output = f"""/* Generated by tools/localization/sync_registry.py; messages live in feature chunks. */
(function (global) {{
  'use strict';
  function deepFreeze(value) {{
    if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value;
    Object.keys(value).forEach(function (key) {{ deepFreeze(value[key]); }});
    return Object.freeze(value);
  }}
  global.__VELORA_LOCALE_REGISTRY__ = deepFreeze({payload});
}})(window);
"""
    temporary = TARGET.with_suffix(TARGET.suffix + ".tmp")
    temporary.write_text(output, encoding="utf-8")
    temporary.replace(TARGET)
    print(
        f"LOCALE_REGISTRY_SYNC_OK locales={len(enabled)} version={manifest['version']} "
        f"bytes={len(output.encode('utf-8'))} preloaded_messages=0"
    )


if __name__ == "__main__":
    main()
